# Generated by Django 3.2.3 on 2021-05-20 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Livros',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=80, verbose_name='titulo')),
                ('autor', models.CharField(max_length=80, verbose_name='autor')),
                ('ano_lancamento', models.IntegerField()),
                ('status', models.CharField(max_length=80, verbose_name='status')),
                ('paginas', models.IntegerField()),
                ('companhia', models.CharField(max_length=80, verbose_name='companhia')),
            ],
            options={
                'verbose_name': 'Livro',
                'verbose_name_plural': 'Livros',
                'db_table': 'Livros',
                'managed': True,
            },
        ),
    ]
